version: '3.2'

services: 
    backend:
        build: ./backend
        container_name: twitter-search-backend
        env_file:
            - backend.env
        ports: 
            - 4000:8080
       
    frontend:
        build: ./frontend
        container_name: twitter-search-frontend
        environment: 
            - BASE_URL=backend:8080
        ports:
            - 8080:5000
        links: 
            - backend        
